repos:
    -   repo: local
        hooks:
        -   id: pip-audit
            name: pip-audit
            entry: pip-audit -r requirements.txt
            language: system
            files: requirements.txt
            pass_filenames: false
        
        -   id: bandit
            name: bandit
            entry: bandit -r src/ -ll --exclude venv
            language: system
            files: \.py$
            pass_filenames: false